### ISSUE TITLE
Dates 

### ISSUE THREAD

**Issue by Jokenry** [chuboyo/smart-emr-project#5]
**Date of Birth:**
This date will be collected and used to automatically update the Patient record continuously, giving us 2 fields like 'DoB' (Date of Birth) and Age, so from the 'DoB' field the current Age of the Patient is calculated.

**Date of Registration:**
This date will be marked or collected by the system as entry is being made and can be queried.

**Comment by chuboyo** [comment]
very nice

**Comment by chuboyo** [comment]
Issue fixed as per recommendations.

**Comment by Jokenry** [comment]
Nicely done Sir.
